"""
Challenge data — generated by scripts/write_challenges.py.

Edit the source script and re-run, or edit individual entries here
directly. Each entry must keep the {prompt, starter_code, tests} shape.
"""

CHALLENGES = { 'basics': { 'prompt': 'Define a function `add(a, b)` that returns the sum of two numbers.',
              'starter_code': 'def add(a, b):\n    # your code here\n    pass\n',
              'tests': [ {'name': 'add(2, 3) returns 5', 'code': 'assert add(2, 3) == 5'},
                         {'name': 'add(-1, 1) returns 0', 'code': 'assert add(-1, 1) == 0'},
                         {'name': 'add(0, 0) returns 0', 'code': 'assert add(0, 0) == 0'}]},
  'data-structures': { 'prompt': 'Build a `unique_in_order(items)` function that returns a list of items with '
                                 'consecutive duplicates removed (but non-consecutive duplicates kept).',
                       'starter_code': 'def unique_in_order(items):\n    # your code here\n    return []\n',
                       'tests': [ { 'name': "['A','A','B','C','C','A'] -> ['A','B','C','A']",
                                    'code': "assert unique_in_order(['A','A','B','C','C','A']) == ['A','B','C','A']"},
                                  {'name': '[] -> []', 'code': 'assert unique_in_order([]) == []'},
                                  {'name': '[1,1,1,1] -> [1]', 'code': 'assert unique_in_order([1,1,1,1]) == [1]'}]},
  'hash-map': { 'prompt': 'Without using `dict`, build a tiny `HashMap` class with `put(key, value)` and `get(key)` '
                          'methods.',
                'starter_code': 'class HashMap:\n'
                                '    def __init__(self):\n'
                                '        self._buckets = [[] for _ in range(16)]\n'
                                '\n'
                                '    def put(self, key, value):\n'
                                '        # your code here\n'
                                '        pass\n'
                                '\n'
                                '    def get(self, key):\n'
                                '        # your code here\n'
                                '        return None\n',
                'tests': [ { 'name': 'get of put returns the value',
                             'code': "h = HashMap(); h.put('a', 1); assert h.get('a') == 1"},
                           { 'name': 'missing key returns None',
                             'code': "h = HashMap(); assert h.get('missing') is None"},
                           { 'name': 'put twice updates the value',
                             'code': "h = HashMap(); h.put('a', 1); h.put('a', 2); assert h.get('a') == 2"}]},
  'json': { 'prompt': 'Given the string `raw = \'{"name": "Alice", "age": 30}\'`, parse it into a dict named `data` '
                      'and increment its `age` by 1.',
            'starter_code': 'import json\nraw = \'{"name": "Alice", "age": 30}\'\n# your code here\ndata = {}\n',
            'tests': [ {'name': 'data is a dict', 'code': 'assert isinstance(data, dict)'},
                       {'name': 'name preserved', 'code': "assert data['name'] == 'Alice'"},
                       {'name': 'age incremented to 31', 'code': "assert data['age'] == 31"}]},
  'regex': { 'prompt': 'Write `find_emails(text)` returning a list of email addresses (simple pattern: word chars, @, '
                       'word chars, ., letters).',
             'starter_code': 'import re\n\ndef find_emails(text):\n    # your code here\n    return []\n',
             'tests': [ { 'name': 'finds one email',
                          'code': "assert find_emails('contact me at a@b.com today') == ['a@b.com']"},
                        { 'name': 'finds multiple emails',
                          'code': "assert find_emails('a@b.com and c@d.org') == ['a@b.com', 'c@d.org']"},
                        { 'name': 'returns [] when none found',
                          'code': "assert find_emails('no addresses here') == []"}]},
  'python-comments': { 'prompt': 'Write a function `square(n)` that has a docstring describing what it does, and '
                                 'returns n squared.',
                       'starter_code': 'def square(n):\n    # add a docstring AND return n squared\n    pass\n',
                       'tests': [ {'name': 'square(4) == 16', 'code': 'assert square(4) == 16'},
                                  { 'name': 'has a docstring',
                                    'code': 'assert isinstance(square.__doc__, str) and len(square.__doc__) > 0'}]},
  'python-variables': { 'prompt': 'Create three variables: `name` (any string), `age` (any int), and `is_learner` set '
                                  'to True.',
                        'starter_code': '# define name, age, is_learner\n',
                        'tests': [ { 'name': 'name is a non-empty string',
                                     'code': 'assert isinstance(name, str) and len(name) > 0'},
                                   {'name': 'age is an int (not bool)', 'code': 'assert type(age) is int'},
                                   {'name': 'is_learner is True', 'code': 'assert is_learner is True'}]},
  'python-data-types': { 'prompt': 'Create one variable of each type: `s` (str), `i` (int), `f` (float), `b` (bool), '
                                   '`lst` (list), `tpl` (tuple), `st` (set), `dct` (dict).',
                         'starter_code': '# create all eight variables\n',
                         'tests': [ { 'name': 'all variables exist with correct types',
                                      'code': 'assert isinstance(s, str)\n'
                                              'assert type(i) is int\n'
                                              'assert isinstance(f, float)\n'
                                              'assert isinstance(b, bool)\n'
                                              'assert isinstance(lst, list)\n'
                                              'assert isinstance(tpl, tuple)\n'
                                              'assert isinstance(st, set)\n'
                                              'assert isinstance(dct, dict)'}]},
  'python-numbers': { 'prompt': 'Write `area_of_circle(radius)` returning the area of a circle. Use `math.pi`.',
                      'starter_code': 'import math\n'
                                      '\n'
                                      'def area_of_circle(radius):\n'
                                      '    # your code here\n'
                                      '    return 0\n',
                      'tests': [ { 'name': 'radius 1 -> pi',
                                   'code': 'import math; assert abs(area_of_circle(1) - math.pi) < 1e-9'},
                                 {'name': 'radius 0 -> 0', 'code': 'assert area_of_circle(0) == 0'},
                                 { 'name': 'radius 2 -> 4*pi',
                                   'code': 'import math; assert abs(area_of_circle(2) - 4 * math.pi) < 1e-9'}]},
  'python-casting': { 'prompt': 'Write `sum_strings(a, b)` that takes two number-strings and returns the integer sum.',
                      'starter_code': 'def sum_strings(a, b):\n    # your code here\n    return 0\n',
                      'tests': [ {'name': "'3' + '4' -> 7", 'code': "assert sum_strings('3', '4') == 7"},
                                 {'name': 'result is an int', 'code': "assert type(sum_strings('1', '2')) is int"},
                                 {'name': 'handles negatives', 'code': "assert sum_strings('-10', '5') == -5"}]},
  'python-strings': { 'prompt': 'Write `reverse_words(text)` that reverses the order of words in a sentence.',
                      'starter_code': "def reverse_words(text):\n    # your code here\n    return ''\n",
                      'tests': [ { 'name': 'reverses three words',
                                   'code': "assert reverse_words('hello world here') == 'here world hello'"},
                                 {'name': 'handles single word', 'code': "assert reverse_words('hi') == 'hi'"},
                                 {'name': 'handles empty string', 'code': "assert reverse_words('') == ''"}]},
  'python-booleans': { 'prompt': 'Write `is_truthy(value)` that returns True for any truthy value and False otherwise.',
                       'starter_code': 'def is_truthy(value):\n    # your code here\n    return False\n',
                       'tests': [ {'name': 'non-empty string is truthy', 'code': "assert is_truthy('hi') is True"},
                                  {'name': '0 is falsy', 'code': 'assert is_truthy(0) is False'},
                                  {'name': 'empty list is falsy', 'code': 'assert is_truthy([]) is False'},
                                  {'name': 'None is falsy', 'code': 'assert is_truthy(None) is False'}]},
  'python-operators': { 'prompt': 'Write `is_even_positive(n)` returning True only when n is both positive and even.',
                        'starter_code': 'def is_even_positive(n):\n    # your code here\n    return False\n',
                        'tests': [ {'name': '4 is even positive', 'code': 'assert is_even_positive(4) is True'},
                                   {'name': '3 is not (odd)', 'code': 'assert is_even_positive(3) is False'},
                                   {'name': '-2 is not (not positive)', 'code': 'assert is_even_positive(-2) is False'},
                                   {'name': '0 is not (not positive)', 'code': 'assert is_even_positive(0) is False'}]},
  'python-lists': { 'prompt': 'Write `second_largest(nums)` returning the second-largest unique value in a list of '
                              'ints.',
                    'starter_code': 'def second_largest(nums):\n    # your code here\n    return 0\n',
                    'tests': [ {'name': 'basic list', 'code': 'assert second_largest([1, 3, 2, 5, 4]) == 4'},
                               {'name': 'duplicates ignored', 'code': 'assert second_largest([5, 5, 4, 3]) == 4'},
                               {'name': 'unsorted input', 'code': 'assert second_largest([10, 7, 8, 2]) == 8'}]},
  'python-tuples': { 'prompt': 'Write `swap(pair)` that takes a 2-tuple and returns it with the elements swapped.',
                     'starter_code': 'def swap(pair):\n    # your code here\n    return pair\n',
                     'tests': [ {'name': '(1, 2) -> (2, 1)', 'code': 'assert swap((1, 2)) == (2, 1)'},
                                {'name': "('a', 'b') -> ('b', 'a')", 'code': "assert swap(('a', 'b')) == ('b', 'a')"},
                                {'name': 'result is still a tuple', 'code': 'assert isinstance(swap((1, 2)), tuple)'}]},
  'python-sets': { 'prompt': 'Write `unique(items)` returning a list of unique items, in any order.',
                   'starter_code': 'def unique(items):\n    # your code here — use a set internally\n    return []\n',
                   'tests': [ { 'name': 'removes duplicates',
                                'code': 'assert sorted(unique([1, 2, 2, 3, 3, 3])) == [1, 2, 3]'},
                              {'name': 'empty list -> []', 'code': 'assert unique([]) == []'},
                              { 'name': 'already-unique list passes through',
                                'code': 'assert sorted(unique([1, 2, 3])) == [1, 2, 3]'}]},
  'python-dictionaries': { 'prompt': 'Write `count_letters(text)` returning a dict mapping each letter to how many '
                                     'times it appears (lowercase, no spaces).',
                           'starter_code': 'def count_letters(text):\n    # your code here\n    return {}\n',
                           'tests': [ { 'name': "counts 'hello'",
                                        'code': "assert count_letters('hello') == {'h': 1, 'e': 1, 'l': 2, 'o': 1}"},
                                      {'name': 'ignores spaces', 'code': "assert count_letters('a a a') == {'a': 3}"},
                                      {'name': 'empty -> {}', 'code': "assert count_letters('') == {}"}]},
  'python-if-else': { 'prompt': "Write `fizzbuzz(n)` returning 'Fizz' for multiples of 3, 'Buzz' for multiples of 5, "
                                "'FizzBuzz' for both, and the number as a string otherwise.",
                      'starter_code': 'def fizzbuzz(n):\n    # your code here\n    return str(n)\n',
                      'tests': [ {'name': "3 -> 'Fizz'", 'code': "assert fizzbuzz(3) == 'Fizz'"},
                                 {'name': "5 -> 'Buzz'", 'code': "assert fizzbuzz(5) == 'Buzz'"},
                                 {'name': "15 -> 'FizzBuzz'", 'code': "assert fizzbuzz(15) == 'FizzBuzz'"},
                                 {'name': "7 -> '7'", 'code': "assert fizzbuzz(7) == '7'"}]},
  'python-match': { 'prompt': "Using a `match` statement, write `describe(color)` returning 'warm' for "
                              "'red'/'orange'/'yellow', 'cool' for 'blue'/'green', and 'unknown' otherwise.",
                    'starter_code': "def describe(color):\n    # use a match statement\n    return 'unknown'\n",
                    'tests': [ {'name': 'red -> warm', 'code': "assert describe('red') == 'warm'"},
                               {'name': 'blue -> cool', 'code': "assert describe('blue') == 'cool'"},
                               {'name': 'purple -> unknown', 'code': "assert describe('purple') == 'unknown'"}]},
  'python-while-loops': { 'prompt': 'Use a while loop in `digits(n)` to return the number of digits in a positive '
                                    'integer n.',
                          'starter_code': 'def digits(n):\n    # your code here, use a while loop\n    return 0\n',
                          'tests': [ {'name': '5 -> 1', 'code': 'assert digits(5) == 1'},
                                     {'name': '42 -> 2', 'code': 'assert digits(42) == 2'},
                                     {'name': '100000 -> 6', 'code': 'assert digits(100000) == 6'}]},
  'python-for-loops': { 'prompt': 'Write `sum_evens(nums)` using a for loop to return the sum of even numbers in the '
                                  'list.',
                        'starter_code': 'def sum_evens(nums):\n    # your code here\n    return 0\n',
                        'tests': [ {'name': '[1, 2, 3, 4] -> 6', 'code': 'assert sum_evens([1, 2, 3, 4]) == 6'},
                                   {'name': 'all odd -> 0', 'code': 'assert sum_evens([1, 3, 5]) == 0'},
                                   {'name': 'empty -> 0', 'code': 'assert sum_evens([]) == 0'}]},
  'python-functions': { 'prompt': "Write `greet(name, greeting='Hello')` that returns `'<greeting>, <name>!'`.",
                        'starter_code': "def greet(name, greeting='Hello'):\n    # your code here\n    return ''\n",
                        'tests': [ {'name': 'default greeting', 'code': "assert greet('Alice') == 'Hello, Alice!'"},
                                   {'name': 'custom greeting', 'code': "assert greet('Bob', 'Hi') == 'Hi, Bob!'"},
                                   { 'name': 'keyword call works',
                                     'code': "assert greet(name='Carol', greeting='Hey') == 'Hey, Carol!'"}]},
  'python-range': { 'prompt': 'Use range() in `multiples_of_three(n)` to return a list of multiples of 3 from 0 up to '
                              '(not including) n.',
                    'starter_code': 'def multiples_of_three(n):\n    # your code here\n    return []\n',
                    'tests': [ {'name': 'n=10 -> [0,3,6,9]', 'code': 'assert multiples_of_three(10) == [0, 3, 6, 9]'},
                               {'name': 'n=0 -> []', 'code': 'assert multiples_of_three(0) == []'},
                               {'name': 'n=3 -> [0]', 'code': 'assert multiples_of_three(3) == [0]'}]},
  'python-arrays': { 'prompt': 'Use `array.array` to make `make_int_array(values)` that returns an int array '
                               'containing the given values.',
                     'starter_code': 'from array import array\n'
                                     '\n'
                                     'def make_int_array(values):\n'
                                     '    # your code here\n'
                                     "    return array('i')\n",
                     'tests': [ { 'name': 'returns an array.array',
                                  'code': 'from array import array; assert isinstance(make_int_array([1, 2, 3]), '
                                          'array)'},
                                {'name': "typecode is 'i'", 'code': "assert make_int_array([1, 2, 3]).typecode == 'i'"},
                                { 'name': 'contains the values',
                                  'code': 'assert list(make_int_array([1, 2, 3])) == [1, 2, 3]'}]},
  'python-iterators': { 'prompt': 'Build a class `Counter` with an `__iter__` that yields 1, 2, ..., n and stops.',
                        'starter_code': 'class Counter:\n'
                                        '    def __init__(self, n):\n'
                                        '        self.n = n\n'
                                        '    # add __iter__\n',
                        'tests': [ {'name': 'iterates 1..n', 'code': 'assert list(Counter(4)) == [1, 2, 3, 4]'},
                                   {'name': 'Counter(0) empty', 'code': 'assert list(Counter(0)) == []'}]},
  'python-modules': { 'prompt': 'Import `math` and write `hypotenuse(a, b)` that returns the length of the hypotenuse '
                                'for legs a and b.',
                      'starter_code': 'import math\n\ndef hypotenuse(a, b):\n    # your code here\n    return 0\n',
                      'tests': [ {'name': '3, 4 -> 5', 'code': 'assert abs(hypotenuse(3, 4) - 5) < 1e-9'},
                                 {'name': '0, 0 -> 0', 'code': 'assert hypotenuse(0, 0) == 0'},
                                 {'name': '5, 12 -> 13', 'code': 'assert abs(hypotenuse(5, 12) - 13) < 1e-9'}]},
  'python-dates': { 'prompt': 'Write `days_between(a, b)` that takes two `date` objects and returns the absolute '
                              'number of days between them.',
                    'starter_code': 'from datetime import date\n'
                                    '\n'
                                    'def days_between(a, b):\n'
                                    '    # your code here\n'
                                    '    return 0\n',
                    'tests': [ { 'name': 'same day -> 0',
                                 'code': 'from datetime import date; assert days_between(date(2026, 1, 1), date(2026, '
                                         '1, 1)) == 0'},
                               { 'name': 'one week',
                                 'code': 'from datetime import date; assert days_between(date(2026, 1, 1), date(2026, '
                                         '1, 8)) == 7'},
                               { 'name': 'negative order',
                                 'code': 'from datetime import date; assert days_between(date(2026, 1, 8), date(2026, '
                                         '1, 1)) == 7'}]},
  'python-math': { 'prompt': 'Write `safe_sqrt(x)` that returns `math.sqrt(x)` if x >= 0, otherwise returns None.',
                   'starter_code': 'import math\n\ndef safe_sqrt(x):\n    # your code here\n    return None\n',
                   'tests': [ {'name': 'sqrt of 16 is 4', 'code': 'assert safe_sqrt(16) == 4'},
                              {'name': 'sqrt of 0 is 0', 'code': 'assert safe_sqrt(0) == 0'},
                              {'name': 'negative returns None', 'code': 'assert safe_sqrt(-1) is None'}]},
  'python-pip': { 'prompt': 'No code to run for this lesson — just write a Python list `commands` containing the three '
                            'pip commands (as strings) to install requests, freeze deps, and upgrade pip.',
                  'starter_code': '# Fill `commands` with three pip command strings.\ncommands = []\n',
                  'tests': [ {'name': 'commands has 3 entries', 'code': 'assert len(commands) == 3'},
                             { 'name': 'install requests command present',
                               'code': "assert any('install' in c and 'requests' in c for c in commands)"},
                             {'name': 'freeze command present', 'code': "assert any('freeze' in c for c in commands)"},
                             { 'name': 'upgrade pip command present',
                               'code': "assert any('upgrade' in c and 'pip' in c for c in commands)"}]},
  'python-try-except': { 'prompt': 'Write `safe_int(s)` that returns int(s) if possible, otherwise returns 0. Use '
                                   'try/except.',
                         'starter_code': 'def safe_int(s):\n    # your code here\n    return 0\n',
                         'tests': [ {'name': 'valid int string', 'code': "assert safe_int('42') == 42"},
                                    {'name': 'invalid -> 0', 'code': "assert safe_int('hello') == 0"},
                                    {'name': 'empty -> 0', 'code': "assert safe_int('') == 0"},
                                    {'name': 'negative', 'code': "assert safe_int('-3') == -3"}]},
  'python-string-formatting': { 'prompt': "Use an f-string in `format_price(name, price)` to return `'<name>: "
                                          "$<price>'` with price shown to exactly 2 decimal places.",
                                'starter_code': "def format_price(name, price):\n    # your code here\n    return ''\n",
                                'tests': [ { 'name': 'apple at 1.5',
                                             'code': "assert format_price('apple', 1.5) == 'apple: $1.50'"},
                                           { 'name': 'milk at 2.999',
                                             'code': "assert format_price('milk', 2.999) == 'milk: $3.00'"},
                                           { 'name': 'free at 0',
                                             'code': "assert format_price('air', 0) == 'air: $0.00'"}]},
  'python-none': { 'prompt': 'Write `first_or_none(items)` returning the first item of a list, or None if the list is '
                             'empty.',
                   'starter_code': 'def first_or_none(items):\n    # your code here\n    return None\n',
                   'tests': [ {'name': 'first of [1,2,3] is 1', 'code': 'assert first_or_none([1, 2, 3]) == 1'},
                              {'name': 'empty -> None', 'code': 'assert first_or_none([]) is None'},
                              {'name': 'first can be falsy', 'code': 'assert first_or_none([0, 1, 2]) == 0'}]},
  'python-user-input': { 'prompt': "Pyodide doesn't support input() in this environment, so for this challenge, define "
                                   "`parse_age(raw)` that takes a string and returns an int, or returns -1 if it isn't "
                                   'a valid age (1-120).',
                         'starter_code': 'def parse_age(raw):\n    # your code here\n    return -1\n',
                         'tests': [ {'name': 'valid age', 'code': "assert parse_age('25') == 25"},
                                    {'name': 'non-numeric -> -1', 'code': "assert parse_age('twenty') == -1"},
                                    {'name': 'out of range -> -1', 'code': "assert parse_age('200') == -1"},
                                    {'name': 'zero -> -1', 'code': "assert parse_age('0') == -1"}]},
  'python-virtualenv': { 'prompt': 'Define `setup_commands` as a list of three shell command strings that, in order: '
                                   'create a venv called .venv, activate it on macOS/Linux, and install from '
                                   'requirements.txt.',
                         'starter_code': '# Define setup_commands\nsetup_commands = []\n',
                         'tests': [ {'name': '3 commands', 'code': 'assert len(setup_commands) == 3'},
                                    { 'name': 'create venv command',
                                      'code': "assert any('venv' in c and '.venv' in c for c in setup_commands)"},
                                    { 'name': 'activate command',
                                      'code': "assert any('activate' in c for c in setup_commands)"},
                                    { 'name': 'pip install -r requirements.txt',
                                      'code': "assert any('pip install' in c and 'requirements.txt' in c for c in "
                                              'setup_commands)'}]},
  'stack': { 'prompt': 'Build a class `Stack` with `push(x)`, `pop()`, and `peek()` methods using a list internally.',
             'starter_code': 'class Stack:\n'
                             '    def __init__(self):\n'
                             '        self._items = []\n'
                             '    # add push, pop, peek\n',
             'tests': [ { 'name': 'push then pop returns the item',
                          'code': 's = Stack(); s.push(1); assert s.pop() == 1'},
                        { 'name': 'LIFO order',
                          'code': 's = Stack()\n'
                                  'for x in [1, 2, 3]: s.push(x)\n'
                                  'assert s.pop() == 3 and s.pop() == 2 and s.pop() == 1'},
                        { 'name': "peek doesn't remove",
                          'code': 's = Stack(); s.push(7); assert s.peek() == 7 and s.peek() == 7'}]},
  'queue': { 'prompt': 'Using collections.deque internally, build a class `Queue` with `enqueue(x)` and `dequeue()` '
                       'methods.',
             'starter_code': 'from collections import deque\n'
                             '\n'
                             'class Queue:\n'
                             '    def __init__(self):\n'
                             '        self._items = deque()\n'
                             '    # add enqueue, dequeue\n',
             'tests': [ { 'name': 'FIFO order',
                          'code': 'q = Queue()\n'
                                  'for x in [1, 2, 3]: q.enqueue(x)\n'
                                  'assert q.dequeue() == 1 and q.dequeue() == 2 and q.dequeue() == 3'},
                        { 'name': 'interleaved',
                          'code': "q = Queue(); q.enqueue('a'); q.enqueue('b'); assert q.dequeue() == 'a'; "
                                  "q.enqueue('c'); assert q.dequeue() == 'b' and q.dequeue() == 'c'"}]},
  'deque': { 'prompt': 'Use `collections.deque` to build `recent(items, n)` which returns the last n items of an '
                       'iterable as a list.',
             'starter_code': 'from collections import deque\n'
                             '\n'
                             'def recent(items, n):\n'
                             '    # your code here — use deque(..., maxlen=n)\n'
                             '    return []\n',
             'tests': [ {'name': 'last 3 of 1..10', 'code': 'assert recent(range(1, 11), 3) == [8, 9, 10]'},
                        {'name': 'n larger than len', 'code': 'assert recent([1, 2], 5) == [1, 2]'},
                        {'name': 'n=0 returns []', 'code': 'assert recent([1, 2, 3], 0) == []'}]},
  'linked-list': { 'prompt': 'Given a Node class with .value and .next, write `length(head)` returning the number of '
                             'nodes in the chain.',
                   'starter_code': 'class Node:\n'
                                   '    def __init__(self, value, next_=None):\n'
                                   '        self.value = value\n'
                                   '        self.next = next_\n'
                                   '\n'
                                   'def length(head):\n'
                                   '    # your code here\n'
                                   '    return 0\n',
                   'tests': [ {'name': 'empty (None) -> 0', 'code': 'assert length(None) == 0'},
                              {'name': 'single node -> 1', 'code': 'assert length(Node(1)) == 1'},
                              { 'name': 'three nodes -> 3',
                                'code': 'h = Node(1, Node(2, Node(3))); assert length(h) == 3'}]},
  'doubly-linked-list': { 'prompt': 'Given Node(prev, value, next) wired manually, write `to_list_backwards(tail)` '
                                    'returning a list of values walking from tail to head via prev pointers.',
                          'starter_code': 'class Node:\n'
                                          '    def __init__(self, value):\n'
                                          '        self.value = value\n'
                                          '        self.prev = None\n'
                                          '        self.next = None\n'
                                          '\n'
                                          'def to_list_backwards(tail):\n'
                                          '    # your code here\n'
                                          '    return []\n',
                          'tests': [ { 'name': 'walks backwards via prev',
                                       'code': 'a = Node(1); b = Node(2); c = Node(3)\n'
                                               'a.next = b; b.prev = a; b.next = c; c.prev = b\n'
                                               'assert to_list_backwards(c) == [3, 2, 1]'},
                                     {'name': 'single node', 'code': 'assert to_list_backwards(Node(7)) == [7]'}]},
  'priority-queue': { 'prompt': 'Use heapq to write `top_k(nums, k)` returning the k largest values, sorted '
                                'descending.',
                      'starter_code': 'import heapq\n\ndef top_k(nums, k):\n    # your code here\n    return []\n',
                      'tests': [ { 'name': 'top 3 of [5,1,9,3,7]',
                                   'code': 'assert top_k([5, 1, 9, 3, 7], 3) == [9, 7, 5]'},
                                 {'name': 'k == len(nums)', 'code': 'assert top_k([2, 1, 3], 3) == [3, 2, 1]'},
                                 {'name': 'k == 0 -> []', 'code': 'assert top_k([1, 2, 3], 0) == []'}]},
  'trie': { 'prompt': 'Build a Trie class with `insert(word)` and `starts_with(prefix)` returning True/False.',
            'starter_code': 'class Trie:\n'
                            '    def __init__(self):\n'
                            '        self.root = {}\n'
                            '    # add insert and starts_with\n',
            'tests': [ { 'name': 'inserts and matches prefix',
                         'code': "t = Trie(); t.insert('apple'); assert t.starts_with('app') is True"},
                       { 'name': 'unknown prefix returns False',
                         'code': "t = Trie(); t.insert('apple'); assert t.starts_with('ban') is False"},
                       { 'name': 'multiple words share prefix',
                         'code': 't = Trie()\n'
                                 "for w in ['cat', 'car', 'cab']: t.insert(w)\n"
                                 "assert t.starts_with('ca') is True"}]},
  'graph': { 'prompt': 'Given an adjacency-list dict, write `neighbors_of(graph, node)` returning a sorted list of '
                       "neighbors. Return [] if node isn't in the graph.",
             'starter_code': 'def neighbors_of(graph, node):\n    # your code here\n    return []\n',
             'tests': [ { 'name': 'node exists',
                          'code': "g = {'A': ['B', 'C'], 'B': ['A']}\nassert neighbors_of(g, 'A') == ['B', 'C']"},
                        { 'name': 'sorted order',
                          'code': "g = {'A': ['Z', 'B', 'C']}\nassert neighbors_of(g, 'A') == ['B', 'C', 'Z']"},
                        {'name': 'node missing -> []', 'code': "assert neighbors_of({'A': ['B']}, 'X') == []"}]},
  'counter': { 'prompt': 'Use collections.Counter to write `most_common_char(text)` returning the most-frequent '
                         'character in `text` (ignore spaces).',
               'starter_code': 'from collections import Counter\n'
                               '\n'
                               'def most_common_char(text):\n'
                               '    # your code here\n'
                               "    return ''\n",
               'tests': [ { 'name': "'mississippi' -> 'i' or 's'",
                            'code': "assert most_common_char('mississippi') in ('i', 's')"},
                          {'name': 'ignores spaces', 'code': "assert most_common_char('a a a b') == 'a'"},
                          {'name': 'single character', 'code': "assert most_common_char('zzz') == 'z'"}]},
  'defaultdict': { 'prompt': 'Use collections.defaultdict to group `pairs` (list of (group, value) tuples) into a dict '
                             'mapping each group to a list of its values.',
                   'starter_code': 'from collections import defaultdict\n'
                                   '\n'
                                   'def group_pairs(pairs):\n'
                                   '    # your code here\n'
                                   '    return {}\n',
                   'tests': [ { 'name': 'groups two teams',
                                'code': "out = group_pairs([('eng', 'a'), ('sales', 'b'), ('eng', 'c')]); assert "
                                        "dict(out) == {'eng': ['a', 'c'], 'sales': ['b']}"},
                              {'name': 'empty input', 'code': 'assert dict(group_pairs([])) == {}'}]},
  'namedtuple': { 'prompt': 'Define a namedtuple `Point` with fields `x` and `y`, then write `distance(p1, p2)` '
                            'returning Euclidean distance between two Points.',
                  'starter_code': 'from collections import namedtuple\n'
                                  'import math\n'
                                  '\n'
                                  '# define Point as a namedtuple\n'
                                  '\n'
                                  'def distance(p1, p2):\n'
                                  '    # your code here\n'
                                  '    return 0\n',
                  'tests': [ {'name': '3-4-5 distance', 'code': 'assert distance(Point(0, 0), Point(3, 4)) == 5'},
                             {'name': 'zero distance', 'code': 'assert distance(Point(1, 1), Point(1, 1)) == 0'},
                             { 'name': 'Point is a namedtuple',
                               'code': "assert hasattr(Point, '_fields') and Point._fields == ('x', 'y')"}]},
  'frozenset': { 'prompt': 'Use frozenset to make `cache_key(items)` return a hashable key representing a set of items '
                           '(order-independent).',
                 'starter_code': 'def cache_key(items):\n    # your code here\n    return None\n',
                 'tests': [ {'name': 'is a frozenset', 'code': 'assert isinstance(cache_key([1, 2, 3]), frozenset)'},
                            { 'name': 'same items different order',
                              'code': 'assert cache_key([1, 2, 3]) == cache_key([3, 2, 1])'},
                            { 'name': 'different items differ',
                              'code': 'assert cache_key([1, 2]) != cache_key([1, 2, 3])'},
                            { 'name': 'usable as a dict key',
                              'code': "d = {cache_key([1, 2]): 'ok'}; assert d[cache_key([2, 1])] == 'ok'"}]},
  'recursion': { 'prompt': 'Write `factorial(n)` recursively. factorial(0) is 1.',
                 'starter_code': 'def factorial(n):\n    # your code here\n    pass\n',
                 'tests': [ {'name': 'factorial(0) == 1', 'code': 'assert factorial(0) == 1'},
                            {'name': 'factorial(1) == 1', 'code': 'assert factorial(1) == 1'},
                            {'name': 'factorial(5) == 120', 'code': 'assert factorial(5) == 120'},
                            {'name': 'factorial(7) == 5040', 'code': 'assert factorial(7) == 5040'}]},
  'linear-search': { 'prompt': 'Write `linear_search(arr, target)` that returns the index of target, or -1 if missing.',
                     'starter_code': 'def linear_search(arr, target):\n    # your code here\n    return -1\n',
                     'tests': [ {'name': 'finds in middle', 'code': 'assert linear_search([1,3,5,7,9], 5) == 2'},
                                {'name': 'returns -1 when absent', 'code': 'assert linear_search([1,3,5], 4) == -1'},
                                {'name': 'finds at start', 'code': 'assert linear_search([1,3,5], 1) == 0'},
                                {'name': 'empty list -> -1', 'code': 'assert linear_search([], 1) == -1'}]},
  'binary-search': { 'prompt': 'Write `binary_search(arr, target)` that returns the index of target in a SORTED list, '
                               'or -1 if not found.',
                     'starter_code': 'def binary_search(arr, target):\n    # your code here\n    return -1\n',
                     'tests': [ {'name': 'finds middle item', 'code': 'assert binary_search([1,3,5,7,9], 5) == 2'},
                                {'name': 'returns -1 missing', 'code': 'assert binary_search([1,3,5,7,9], 4) == -1'},
                                {'name': 'finds at end', 'code': 'assert binary_search([1,2,3,4,5], 5) == 4'},
                                {'name': 'handles empty', 'code': 'assert binary_search([], 1) == -1'}]},
  'bubble-sort': { 'prompt': "Write `bubble_sort(arr)` returning a new sorted list. Don't mutate the input.",
                   'starter_code': 'def bubble_sort(arr):\n    # your code here\n    return arr\n',
                   'tests': [ {'name': 'sorts a small list', 'code': 'assert bubble_sort([3, 1, 2]) == [1, 2, 3]'},
                              {'name': 'handles empty', 'code': 'assert bubble_sort([]) == []'},
                              { 'name': "doesn't mutate",
                                'code': 'orig=[3,1,2]; _=bubble_sort(orig); assert orig==[3,1,2]'},
                              {'name': 'handles duplicates', 'code': 'assert bubble_sort([2,1,2,1]) == [1,1,2,2]'}]},
  'selection-sort': { 'prompt': "Write `selection_sort(arr)` returning a new sorted list. Don't mutate the input.",
                      'starter_code': 'def selection_sort(arr):\n    # your code here\n    return arr\n',
                      'tests': [ { 'name': 'sorts a small list',
                                   'code': 'assert selection_sort([3, 1, 2]) == [1, 2, 3]'},
                                 {'name': 'handles empty', 'code': 'assert selection_sort([]) == []'},
                                 { 'name': "doesn't mutate",
                                   'code': 'orig=[3,1,2]; _=selection_sort(orig); assert orig==[3,1,2]'},
                                 {'name': 'already sorted', 'code': 'assert selection_sort([1,2,3,4]) == [1,2,3,4]'}]},
  'insertion-sort': { 'prompt': "Write `insertion_sort(arr)` returning a new sorted list. Don't mutate the input.",
                      'starter_code': 'def insertion_sort(arr):\n    # your code here\n    return arr\n',
                      'tests': [ { 'name': 'sorts a small list',
                                   'code': 'assert insertion_sort([5, 2, 4, 6, 1, 3]) == [1, 2, 3, 4, 5, 6]'},
                                 {'name': 'handles empty', 'code': 'assert insertion_sort([]) == []'},
                                 { 'name': "doesn't mutate",
                                   'code': 'orig=[3,1,2]; _=insertion_sort(orig); assert orig==[3,1,2]'},
                                 {'name': 'single element', 'code': 'assert insertion_sort([7]) == [7]'}]},
  'merge-sort': { 'prompt': 'Write `merge_sort(arr)` returning a new sorted list using the divide-and-conquer merge '
                            'sort algorithm.',
                  'starter_code': 'def merge_sort(arr):\n    # your code here\n    return arr\n',
                  'tests': [ { 'name': 'sorts a medium list',
                               'code': 'assert merge_sort([5,2,8,1,9,3]) == [1,2,3,5,8,9]'},
                             {'name': 'handles empty', 'code': 'assert merge_sort([]) == []'},
                             {'name': 'single element', 'code': 'assert merge_sort([7]) == [7]'},
                             { 'name': 'handles duplicates',
                               'code': 'assert merge_sort([3,3,1,1,2,2]) == [1,1,2,2,3,3]'}]},
  'quicksort': { 'prompt': 'Write `quicksort(arr)` returning a new sorted list using the quicksort algorithm.',
                 'starter_code': 'def quicksort(arr):\n    # your code here\n    return arr\n',
                 'tests': [ {'name': 'sorts a medium list', 'code': 'assert quicksort([5,2,8,1,9,3]) == [1,2,3,5,8,9]'},
                            {'name': 'handles empty', 'code': 'assert quicksort([]) == []'},
                            {'name': 'single element', 'code': 'assert quicksort([7]) == [7]'},
                            { 'name': 'handles duplicates',
                              'code': 'assert quicksort([3,3,1,1,2,2]) == [1,1,2,2,3,3]'}]},
  'two-pointers': { 'prompt': 'Given a SORTED list `nums` and a `target`, write `has_pair_with_sum(nums, target)` '
                              'returning True if any two elements sum to target. Use the two-pointers pattern.',
                    'starter_code': 'def has_pair_with_sum(nums, target):\n'
                                    '    # your code here — use two pointers\n'
                                    '    return False\n',
                    'tests': [ {'name': 'finds 4+7=11', 'code': 'assert has_pair_with_sum([1,3,4,7,11], 11) is True'},
                               { 'name': 'no pair sums to 100',
                                 'code': 'assert has_pair_with_sum([1,3,4,7,11], 100) is False'},
                               {'name': 'empty list -> False', 'code': 'assert has_pair_with_sum([], 5) is False'},
                               { 'name': 'single element -> False',
                                 'code': 'assert has_pair_with_sum([3], 6) is False'}]},
  'sliding-window': { 'prompt': 'Write `max_window_sum(nums, k)` returning the largest sum of any k consecutive '
                                'elements in nums.',
                      'starter_code': 'def max_window_sum(nums, k):\n    # your code here\n    return 0\n',
                      'tests': [ { 'name': 'max sum of 3',
                                   'code': 'assert max_window_sum([1,4,2,10,23,3,1,0,20], 3) == 36'},
                                 {'name': 'max sum of 1', 'code': 'assert max_window_sum([5,1,8,2], 1) == 8'},
                                 {'name': 'k equals length', 'code': 'assert max_window_sum([1,2,3], 3) == 6'},
                                 {'name': 'k larger than list -> 0', 'code': 'assert max_window_sum([1,2], 5) == 0'}]},
  'memoization': { 'prompt': 'Write a memoized `fib(n)` that returns the nth Fibonacci number. Use functools.lru_cache '
                             'OR a manual dict — either is fine. fib(0)=0, fib(1)=1.',
                   'starter_code': 'from functools import lru_cache\n'
                                   '\n'
                                   'def fib(n):\n'
                                   '    # your code here — memoize so fib(100) returns instantly\n'
                                   '    return 0\n',
                   'tests': [ {'name': 'fib(0) == 0', 'code': 'assert fib(0) == 0'},
                              {'name': 'fib(1) == 1', 'code': 'assert fib(1) == 1'},
                              {'name': 'fib(10) == 55', 'code': 'assert fib(10) == 55'},
                              { 'name': 'fib(35) returns instantly',
                                'code': 'import time; t=time.time(); assert fib(35) == 9227465; assert time.time()-t < '
                                        '0.5'}]}}
