"""add password_reset_at to user

`email` was already unique + non-null as of the initial schema (0001), so
no change is needed there — this migration only adds the column the
forgot-password flow uses to stamp resets and invalidate stale tokens
and sessions.

Revision ID: 1d5088324303
Revises: 0001
Create Date: 2026-07-08 15:18:56.127737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d5088324303'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_reset_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password_reset_at')

    # ### end Alembic commands ###
